services:
  mysql:
    image: mysql:8.0
    container_name: security-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: security_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: security-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql:3306/security_db
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=password
    ports:
      - "8080:8080"

volumes:
  mysql-data:
