spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/security_db
    username: root
    password: password
  security:
    user:
      name: admin
      password: admin
  redis:
    host: localhost
    port: 6379
    timeout: 2000
  cache:
    type: none
    redis:
      time-to-live: 3600000
      cache-null-values: false

server:
  port: 8080

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000 # 1 day in milliseconds

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.config: DEBUG
    org.springframework.data.redis: DEBUG
    com.bcp.security: DEBUG
    io.r2dbc.mysql: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
