spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/security_db
    username: root
    password: password
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000 # 1 day in milliseconds

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.security: DEBUG
    com.bcp.security: DEBUG
    io.r2dbc.mysql: DEBUG
